In [1]:
import tensorflow as tf

In [2]:
tf.version

<module 'tensorflow_core._api.v2.version' from '/Users/austin/.pyenv/versions/anaconda3-5.3.1/envs/tf2/lib/python3.7/site-packages/tensorflow_core/_api/v2/version/__init__.py'>

In [3]:
# 定义一个随机数（标量）
random_float = tf.random.uniform(shape=())

# 定义一个有2个元素的零向量
zero_vector = tf.zeros(shape=(2))

# 定义两个2×2的常量矩阵
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])

In [5]:
# 查看矩阵A的形状、类型和值
print(A.shape)      # 输出(2, 2)，即矩阵的长和宽均为2
print(A.dtype)      # 输出<dtype: 'float32'>
print(A.numpy())    # 输出[[1. 2.]
                    #      [3. 4.]]
print(A)

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [8]:
C = tf.add(A, B)    # 计算矩阵A和B的和
D = tf.matmul(A, B) # 计算矩阵A和B的乘积
print(C,D)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [17]:
x = tf.Variable(initial_value=4.)
with tf.GradientTape() as tape:     # 在 tf.GradientTape() 的上下文内，所有计算步骤都会被记录以用于求导
    y = tf.add(tf.(x),1)
y_grad = tape.gradient(y, x)        # 计算y关于x的导数
print(y,"\n",y_grad)

tf.Tensor(17.0, shape=(), dtype=float32) 
 tf.Tensor(8.0, shape=(), dtype=float32)
